export default {
  LOCAL_STORAGE_USER_INFO_KEY: 'LOCAL_STORAGE_USER_INFO_KEY',
  BASE_REPOSITORY_NAME_KEY: 'BASE_REPOSITORY_NAME',
  BASE_REPOSITORY_NAME: 'Dictronary2',
  GITEE_DIRECTORY_TREE: 'GITEE_DIRECTORY_TREE',
  AK_SK_KEY: 'AK_SK_KEY',
  SIDEBAR_INFO: 'SIDEBAR_INFO',
  SIDEBAR_DEFAULT_WIDTH: 20,
}
